export const CREATE_CLIENT = 'CREATE_CLIENT';
export const FETCH_CLIENT_LIST = 'FETCH_CLIENT_LIST';
// export const FETCH_CLIENT = 'FETCH_CLIENT'
export const SELECT_CLIENT = 'SELECT_CLIENT';
export const TOG_CLIENT_STATUS = 'TOG_CLIENT_STATUS';
export const UPDATE_CLIENT_FILTER = 'UPDATE_CLIENT_FILTER';
export const RESET_SELECTED_CLIENT = 'RESET_SELECTED_CLIENT';